
let wantedCriterias = {
        schoolName: '',
        selectedLocation: [ 'Central and Western', 'Eastern', 'Kowloon city' ],
        day1: false,
        day2: false,
        day3: false,
        day4: false
      }


let SD1 = [
    {
      school_id: 1,
      am_student: 50,
      pm_student: 60,
      full_day_student: null,
      long_full_day_student: null,
      full_day_tuition: null,
      long_full_day_tuition: null,
      has_subsidy: true,
      subsidy_amt: 1800,
      has_am: true,
      has_pm: true,
      has_full_day: false,
      has_long_full_day: false,
      no_of_teacher: 40,
      created_at: 2024-01-18T06:52:44.304Z,
      updated_at: 2024-01-18T06:52:44.304Z,
      profile_pic: 'https://i0.wp.com/hongkongschools.com.hk/wp-content/uploads/listing-uploads/gallery/2022/04/ESF-International-Kindergarten-Hillside-1.jpg?fit=5472%2C3648&ssl=1',
      school_name: 'Happy Kindergarten',
      location: 'Wong Tai Sin',
      am_tuition: null,
      pm_tuition: null,
      half_day_tuition: '0'
    },
    {
      school_id: 2,
      am_student: 48,
      pm_student: 46,
      full_day_student: 14,
      long_full_day_student: null,
      full_day_tuition: 5400,
      long_full_day_tuition: null,
      has_subsidy: true,
      subsidy_amt: 1500,
      has_am: true,
      has_pm: true,
      has_full_day: true,
      has_long_full_day: false,
      no_of_teacher: 38,
      created_at: 2024-01-18T06:52:44.304Z,
      updated_at: 2024-01-18T06:52:44.304Z,
      profile_pic: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/HK_Peak_Guildford_Road_German_Swiss_Intl_Sch_L.JPG',
      school_name: 'Everyday Kindergarten',
      location: 'Central',
      am_tuition: null,
      pm_tuition: null,
      half_day_tuition: '1700'
    },
    {
      school_id: 3,
      am_student: 48,
      pm_student: 46,
      full_day_student: 14,
      long_full_day_student: null,
      full_day_tuition: 5400,
      long_full_day_tuition: null,
      has_subsidy: true,
      subsidy_amt: 1500,
      has_am: true,
      has_pm: true,
      has_full_day: true,
      has_long_full_day: false,
      no_of_teacher: 38,
      created_at: 2024-01-18T06:52:44.304Z,
      updated_at: 2024-01-18T06:52:44.304Z,
      profile_pic: 'https://hf.creative.edu.hk/wp-content/uploads/sites/34/2022/01/00D7942C-FF5D-4377-AACA-DCDE11EB3E28.jpeg',
      school_name: 'Creative Kindergarten',
      location: 'Eastern',
      am_tuition: null,
      pm_tuition: null,
      half_day_tuition: '1700'
    },
    {
      school_id: 4,
      am_student: 48,
      pm_student: 46,
      full_day_student: 14,
      long_full_day_student: null,
      full_day_tuition: 5400,
      long_full_day_tuition: null,
      has_subsidy: true,
      subsidy_amt: 1500,
      has_am: true,
      has_pm: true,
      has_full_day: true,
      has_long_full_day: false,
      no_of_teacher: 38,
      created_at: 2024-01-18T06:52:44.304Z,
      updated_at: 2024-01-18T06:52:44.304Z,
      profile_pic: 'https://media.timeout.com/images/105663276/750/422/image.jpg',
      school_name: 'Causeway Bay Victoria Kindergarten and International Nursery',
      location: 'Wan Chai',
      am_tuition: null,
      pm_tuition: null,
      half_day_tuition: '1700'
    },
    {
      school_id: 5,
      am_student: 48,
      pm_student: 46,
      full_day_student: 14,
      long_full_day_student: null,
      full_day_tuition: 5400,
      long_full_day_tuition: null,
      has_subsidy: true,
      subsidy_amt: 1500,
      has_am: true,
      has_pm: true,
      has_full_day: true,
      has_long_full_day: false,
      no_of_teacher: 38,
      created_at: 2024-01-18T06:52:44.304Z,
      updated_at: 2024-01-18T06:52:44.304Z,
      profile_pic: 'https://www.itseducation.asia/assets/images/article-images/3bdbf_9eb44_mvcps_(1).jpg',
      school_name: 'Malvern College Pre-School Hong Kong',
      location: 'Central and Western',
      am_tuition: null,
      pm_tuition: null,
      half_day_tuition: '1700'
    }
  ]