export const schoolCompare = [
    {
    profile_pic: 'https://firebasestorage.googleapis.com/v0/b/capstone-project-83c20.appspot.com/o/school1.jpg?alt=media&token=e95053a8-1d9f-440a-ac10-aa07cf04a64a',
    school_name: 'The Best Kindergarten',
    location: 'Central and Western',
    address: '101, kindergarten road, CWB, Hong Kong',
    day: 'Half day',
    school_size: 10000,
    no_of_teacher: 100,
    follower: 1000,
    score: 4.5,
    has_am: true,
    has_pm: true,
    has_full_day: false,
    has_long_full_day: false,
    total_student: 1000,
    am_student: 250,
    pm_student: 250,
    full_day_student: 250,
    long_full_day_student: 250,
    half_day_tuition: 1000,
    full_day_tuition: 2000,
    long_full_day_tuition: 4000,
    has_subsidy: true,
    subsidy_amt: 1000
},
{
    profile_pic: 'https://firebasestorage.googleapis.com/v0/b/capstone-project-83c20.appspot.com/o/school2.png?alt=media&token=d43102bc-afeb-49a2-9afe-2d32e20d2705',
    school_name: 'Good Kindergarten',
    location: 'Yau Tsim Mong',
    address: 'Good Road, TST, Hong Kong',
    day: 'Half day',
    school_size: 5000,
    no_of_teacher: 200,
    follower: 800,
    score: 4.2,
    has_am: true,
    has_pm: false,
    has_full_day: true,
    has_long_full_day: false,
    total_student: 800,
    am_student: 200,
    pm_student: 200,
    full_day_student: 200,
    long_full_day_student: 200,
    half_day_tuition: 1500,
    full_day_tuition: 2000,
    long_full_day_tuition: 4500,
    has_subsidy: false,
    subsidy_amt: ''
}]